apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.6.0
    valuesInline: 
      namespace: system-apps
      fullnameOverride: sealed-secrets-controller
    includeCRDs: true
