apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: system-apps
spec:
  description: All system apps should be a member of this project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: user
  namespace: system-apps
spec:
  description: All user apps should be a member of this project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'