apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: system-apps-privileged
helmCharts:
  - name: openebs
    version: 3.3.0
    repo: https://openebs.github.io/charts
    valuesFile: values.yaml
    releaseName: openebs
    includeCRDs: true
    namespace: system-apps-privileged
